[build]
  command = "yarn build"
  ignore = "git diff --quiet HEAD^ HEAD ."
  publish = "dist"

[build.environment]
  YARN_VERSION = "1.21.1"
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
